name: NMFS Openscapes JupyterHub workshop request
description: Reserve the NMFS Openscapes Jupyter Hub for your workshop
title: "[Workshop]: YYYY-MM-DD <brief description>"
labels: "workshop"
assignees:
  - ateucher
  - eeholmes
projects: 
  - "nmfs-openscapes/35"
body:
  - type: markdown
    attributes:
      value: >
        Thank you for your interest in hosting a workshop using the NMFS
        Openscapes JupyterHub! Use this issue to reserve access to the hub at
        https://workshop.nmfs-openscapes.2i2c.cloud.


        Before submitting, please check the
        [workshop spreadsheet](https://docs.google.com/spreadsheets/d/1Y4qzqWLsKHTNzuQi-fOaHGud0Ld_q1GHAzhS9-grV7Q/edit?usp=sharing)
        for any existing reservations around your dates. See also the
        [documentation on openscapes.cloud](https://openscapes.cloud/password-access.html)
        for detailed instructions.


        Fill out the form below and we will get back to you as soon as possible
        to confirm your reservation.

  - type: textarea
    id: workshop-description
    attributes:
      label: Workshop Description
      description: Please provide a brief description of your workshop.
    validations:
      required: true

  - type: input
    id: workshop-start-date
    attributes:
      label: Workshop Start Date
      description: Please provide the start date of your workshop.
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: input
    id: workshop-end-date
    attributes:
      label: Workshop End Date
      description: >
        Please provide the end date of your workshop. Leave blank if it's a 
        one-day workshop.
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: input
    id: workshop-start-time
    attributes:
      label: Workshop Start Time
      description: >
        Please provide the start time (including timezone) of your workshop.
      placeholder: 10:00 AM PST
    validations:
      required: false

  - type: input
    id: workshop-end-time
    attributes:
      label: Workshop End Time
      description: >
        Please provide the end time (including timezone) of your workshop.
      placeholder: 2:00 PM PST
    validations:
      required: false

  - type: input
    id: workshop-url
    attributes:
      label: Workshop URL
      description: Please provide a URL for your workshop (if available).
      placeholder: https://example.com/workshop
    validations:
      required: false

  - type: input
    id: reset-date
    attributes:
      label: Reset Date
      description: >
        By default the password will be reset and participants' home directories
        erased seven days after the workshop ends. If you want the participants
        to have more or less access than the default of seven days, please specify.
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: input
    id: num-participants
    attributes:
      label: Estimated Number of Participants
      description: >
        Please provide an estimate of the number of participants attending 
        your workshop.
    validations:
      required: true

  - type: textarea
    id: compute-requirements
    attributes:
      label: Compute Requirements
      description: >
        What size compute resources will participants be asked to select when 
        they log in? 2Gb (default), 4Gb, more? This is selected in the dropdown 
        at the Hub login, and knowing what you will need helps us make sure the 
        hub is adequately provisioned.
    validations:
      required: true

  - type: textarea
    id: image-requirements
    attributes:
      label: Image Requirements
      description: >
        Will you be using one of the default images, or a custom image?
        Confirm that the image you will be using is sufficient for your needs
        (i.e., has the packages and sufficient versions you need), or that you
        have created an image that can be used by participants.
    validations:
      required: false

  - type: textarea
    id: storage-requirements
    attributes:
      label: Storage Requirements
      description: >
        Are there any special storage needs? Like will participants need access
        to large shared files? Do you anticipate that participants might download
        lots (10s of Gb or more) of data? If so, we will work with you on how best
        to do that in the workshop. We have a S3 scratch bucket and a shared drive
        so that we don't have 10s of copies of big data sets.
    validations:
      required: false

  - type: checkboxes
    id: checklist-organizer-hub-poc
    attributes:
      label: >
        Checklist for workshop organizer (person planning/leading the workshop) 
        and hub point-of-contact (PoC; Openscapes team member helping with hub 
        setup and logistics. Usually @ateucher).
      options:
        - label: >
            **Hub PoC**: Send confirmation to organizer that the request is 
            received and the hub is available for the workshop (a comment in 
            this issue thread is fine)
        - label: >
            **Organizer**: Add your event in the 
            [workshop spreadsheet](https://docs.google.com/spreadsheets/d/14GDUFU3_H2bZcSt--VGLRmrRFq3dylDL8ZeAKuFbV6E/edit?gid=695033382).
            Please check if there are any other workshops scheduled around the 
            same time and if so, let the hub PoC know to make sure the hub can 
            support multiple workshops at the same time.
        - label: >
            **Organizer**: Submit a ticket by email to 2i2c for the workshop 
            [as per instructions](https://openscapes.cloud/password-access.html), 
            cc'ing hub PoC (andy [at] openscapes [dot] org).
        - label: >
            **Hub PoC**: Confirm `[Event]` or `[Support]` issue opened in 
            [2i2c-org/infrastructure](https://github.com/2i2c-org/infrastructure/issues)
            in response to ticket ([example](https://github.com/2i2c-org/infrastructure/issues/5466))
        - label: >
            **Hub PoC**: Add new password and dates to 
            [workshop password spreadsheet](https://docs.google.com/spreadsheets/d/1Y4qzqWLsKHTNzuQi-fOaHGud0Ld_q1GHAzhS9-grV7Q/edit?gid=1793413915).
        - label: >
            **Organizer**: Two weeks before event. I have tested the default hub
            images on the nmfs-openscapes.2i2c.cloud hub or conferred with hub 
            PoC on plan for a workshop specific image.
        - label: >
            **Organizer**: In the week before the event (or when PoC indicates
            password should be live). I tested that the workshop password works 
            and images work.
        - label: >
            **Hub PoC**: After event, put in a 2i2c ticket to remove the 
            participants directories, cleared shared-public, and reset password.
        - label: >
            **Organizer**: After the event, open an 
            [issue](https://github.com/NMFS-Openscapes/workshop-planning/issues/new?template=NMFS-openscapes-workshop-reporting-template.md) 
            in the Workshop Planning repo to report back.

  - type: markdown
    attributes:
      value: >
        ---

        _Please click on the "Projects" button below and tick the 
        "Main Planning" project if it is available to you_
